In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Zadanie 1

In [2]:
import pandas as pd


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/PAD colab/04/Zadanie_1.csv',sep=';')
df

x1    x2    x3    x4    x5    x6    x7    x8    x9   x10   x11    x12  \
0   36.0  27.0  71.0   8.1  3.34  11.4  81.5  3243   8.8  42.6  11.7   21.0   
1   35.0  23.0  72.0  11.1  3.14  11.0  78.8  4281   3.6  50.7  14.4    8.0   
2   44.0  29.0  74.0  10.4  3.21   9.8  81.6  4260   0.8  39.4   NaN    6.0   
3   47.0  45.0  79.0   6.5  3.41  11.1  77.5  3125  27.1  50.2  20.6   18.0   
4   43.0  35.0  77.0   7.6  3.44   9.6  84.6  6441  24.4  43.7  14.3   43.0   
5   53.0  45.0  80.0   7.7  3.45  10.2  66.8  3325  38.5  43.1  25.5   30.0   
6   43.0  30.0  74.0  10.9  3.23  12.1  83.9  4679   3.5  49.2  11.3   21.0   
7   45.0  30.0  73.0   9.3  3.29  10.6  86.0  2140   5.3  40.4  10.5    6.0   
8   36.0  24.0  70.0   9.0  3.31  10.5  83.2  6582   8.1  42.5  12.6   18.0   
9   36.0  27.0  72.0   9.5  3.36  10.7  79.3  4213   6.7  41.0  13.2   12.0   
10  52.0  42.0  79.0   7.7  3.39   9.6  69.2  2302  22.2  41.3  24.2   18.0   
11  33.0  26.0  76.0   8.6  3.20  10.9  83.4  6122  16.3  44.9  10.7   88.0   
12  40.0  34.0  77.0   9.2  3.21  10.2  77.0  4101  13.0  45.7  15.1   26.0   
13  35.0  28.0  71.0   8.8  3.29  11.1  86.3  3042  14.7  44.6  11.4   31.0   
14  37.0  31.0  75.0   8.0  3.26  11.9  78.4  4259  13.1  49.6  13.9   23.0   
15  35.0  46.0  85.0   7.1  3.22  11.8  79.9  1441  14.8  51.2  16.1    1.0   
16  36.0  30.0  75.0   7.5  3.35  11.4  81.9  4029  12.4  44.0  12.0    6.0   
17  15.0  30.0  73.0   8.2  3.15  12.2  84.2  4824   4.7  53.1  12.7   17.0   
18  31.0  27.0  74.0   7.2  3.44  10.8  87.0  4834  15.8  43.5  13.6   52.0   
19   NaN  24.0  72.0   6.5  3.53  10.8  79.5  3694  13.1  33.8  12.4   11.0   
20  31.0  45.0  85.0   7.3  3.22  11.4  80.7  1844  11.5  48.1  18.5    1.0   
21  31.0  24.0  72.0   9.0  3.37  10.9  82.8  3226   5.1  45.2  12.3    5.0   
22  42.0  40.0  77.0   6.1  3.45  10.4  71.8  2269  22.7  41.4  19.5    8.0   
23  43.0  27.0  72.0   9.0  3.25  11.5  87.1  2909   7.2  51.6   9.5    7.0   
24  46.0  55.0  84.0   5.6  3.35  11.4  79.7  2647  21.0  46.9  17.9    6.0   
25  39.0   NaN  76.0   8.7  3.23  11.4  78.6  4412  15.6  46.6  13.2   13.0   
26  35.0  31.0  81.0   9.2  3.10  12.0  78.3  3262  12.6  48.6  13.9    7.0   
27   NaN  32.0  74.0  10.1  3.38   9.5  79.2  3214   2.9  43.7  12.0   11.0   
28  11.0  53.0  68.0   9.2  2.99  12.1  90.6  4700   7.8  48.9  12.3  648.0   
29  30.0  35.0  71.0   8.3  3.37   9.9  77.4  4474  13.1  42.6  17.7   38.0   
30  50.0  42.0  82.0   7.3  3.49  10.4  72.5  3497  36.7  43.3  26.4   15.0   
31  60.0  67.0  82.0  10.0  2.98  11.5  88.6  4657  13.6  47.3  22.4    NaN   
32   NaN   NaN  69.0   8.8  3.26  11.1   NaN  2934   5.8  44.0   9.4   33.0   
33  25.0  12.0  73.0   9.2  3.28  12.1  83.1  2095   2.0  51.9   9.8   20.0   
34  45.0  40.0  80.0   8.3  3.32  10.1  70.3  2682  21.0  46.1  24.1   17.0   
35  46.0  30.0   NaN  10.2  3.16  11.3  83.2  3327   NaN  45.3  12.2    4.0   
36  54.0  54.0  81.0   7.4  3.36   9.7  72.8  3172  31.4  45.5  24.2    NaN   
37  42.0  33.0  77.0   9.7  3.30  10.7  83.5  7462  11.3  48.7  12.4   41.0   
38  42.0  32.0  76.0   9.1  3.32  10.5  87.5  6092  17.5  45.3  13.2   29.0   
39  36.0  29.0  72.0   9.5  3.32  10.6  77.6  3437   8.1  45.5  13.8   45.0   
40  37.0  38.0  67.0  11.3  2.99  12.0  81.5  3387   3.6  50.3  13.5   56.0   
41  42.0  29.0  72.0  10.7  3.19  10.1  79.5  3508   2.2  38.3  15.7    6.0   
42  41.0  33.0  77.0  11.2  3.80   9.6  79.9  4843   2.7  38.6  14.1   11.0   
43  44.0  39.0  78.0   8.2  3.32  11.0  79.9  3768  28.6  49.5  17.5   12.0   
44  32.0  25.0  72.0  10.9  3.21   NaN  82.5  4355   5.0  46.4  10.8    7.0   
45  34.0  32.0  79.0   9.3  3.23   9.7  76.8  5160  17.2  45.1  15.3   31.0   
46  10.0  55.0  70.0   7.3  3.11  12.1  88.9  3033   5.9  51.0  14.0  144.0   
47  18.0  48.0  63.0   9.2  2.92  12.2  87.7  4253  13.7  51.2  12.0  311.0   
48  13.0  49.0  68.0   7.0  3.36  12.2  90.7  2702   3.0  51.9   9.7  105.0   
49  35.0  40.0  64.0   9.6  3.20  12.2  82.5  3626   5.7

In [ ]:
ilosc_wszystkich_komórek = len(df) * len(df.columns)
ilosc_wszystkich_komórek

960

In [ ]:
ilość_niepustych_komórek = df.count().sum()
ilość_niepustych_komórek

940

In [ ]:
ilosc_wierszy = len(df)
ilosc_wierszy

60

In [ ]:
ilosc_kolumn = len(df.columns)
ilosc_kolumn

16

In [ ]:
df.mean()

x1       37.464286
x2       35.368421
x3       74.644068
x4        8.798333
x5        3.280847
x6       10.971186
x7       80.837288
x8     3876.050000
x9       11.925424
x10      46.073333
x11      14.406780
x12      38.758621
x13      22.982759
x14      51.508772
x15      57.533333
Y       940.358433
dtype: float64

In [ ]:
df.median()

x1       38.000
x2       32.000
x3       74.000
x4        9.000
x5        3.280
x6       11.000
x7       81.000
x8     3567.000
x9       11.300
x10      45.500
x11      13.200
x12      14.500
x13       9.000
x14      28.000
x15      57.000
Y       943.683
dtype: float64

In [ ]:
#wariancja
df.var()

x1     1.041442e+02
x2     1.441654e+02
x3     2.299182e+01
x4     2.144912e+00
x5     2.053892e-02
x6     7.265693e-01
x7     2.653652e+01
x8     2.114414e+06
x9     8.077055e+01
x10    2.140775e+01
x11    1.753650e+01
x12    8.728993e+03
x13    2.216614e+03
x14    3.792362e+03
x15    2.981243e+01
Y      3.869621e+03
dtype: float64

In [ ]:
dfd = df.dropna()

In [ ]:
dfd

x1    x2    x3    x4    x5    x6    x7    x8    x9   x10   x11    x12  \
1   35.0  23.0  72.0  11.1  3.14  11.0  78.8  4281   3.6  50.7  14.4    8.0   
3   47.0  45.0  79.0   6.5  3.41  11.1  77.5  3125  27.1  50.2  20.6   18.0   
5   53.0  45.0  80.0   7.7  3.45  10.2  66.8  3325  38.5  43.1  25.5   30.0   
6   43.0  30.0  74.0  10.9  3.23  12.1  83.9  4679   3.5  49.2  11.3   21.0   
7   45.0  30.0  73.0   9.3  3.29  10.6  86.0  2140   5.3  40.4  10.5    6.0   
8   36.0  24.0  70.0   9.0  3.31  10.5  83.2  6582   8.1  42.5  12.6   18.0   
9   36.0  27.0  72.0   9.5  3.36  10.7  79.3  4213   6.7  41.0  13.2   12.0   
10  52.0  42.0  79.0   7.7  3.39   9.6  69.2  2302  22.2  41.3  24.2   18.0   
11  33.0  26.0  76.0   8.6  3.20  10.9  83.4  6122  16.3  44.9  10.7   88.0   
12  40.0  34.0  77.0   9.2  3.21  10.2  77.0  4101  13.0  45.7  15.1   26.0   
14  37.0  31.0  75.0   8.0  3.26  11.9  78.4  4259  13.1  49.6  13.9   23.0   
15  35.0  46.0  85.0   7.1  3.22  11.8  79.9  1441  14.8  51.2  16.1    1.0   
16  36.0  30.0  75.0   7.5  3.35  11.4  81.9  4029  12.4  44.0  12.0    6.0   
17  15.0  30.0  73.0   8.2  3.15  12.2  84.2  4824   4.7  53.1  12.7   17.0   
18  31.0  27.0  74.0   7.2  3.44  10.8  87.0  4834  15.8  43.5  13.6   52.0   
20  31.0  45.0  85.0   7.3  3.22  11.4  80.7  1844  11.5  48.1  18.5    1.0   
21  31.0  24.0  72.0   9.0  3.37  10.9  82.8  3226   5.1  45.2  12.3    5.0   
22  42.0  40.0  77.0   6.1  3.45  10.4  71.8  2269  22.7  41.4  19.5    8.0   
24  46.0  55.0  84.0   5.6  3.35  11.4  79.7  2647  21.0  46.9  17.9    6.0   
26  35.0  31.0  81.0   9.2  3.10  12.0  78.3  3262  12.6  48.6  13.9    7.0   
28  11.0  53.0  68.0   9.2  2.99  12.1  90.6  4700   7.8  48.9  12.3  648.0   
29  30.0  35.0  71.0   8.3  3.37   9.9  77.4  4474  13.1  42.6  17.7   38.0   
30  50.0  42.0  82.0   7.3  3.49  10.4  72.5  3497  36.7  43.3  26.4   15.0   
33  25.0  12.0  73.0   9.2  3.28  12.1  83.1  2095   2.0  51.9   9.8   20.0   
34  45.0  40.0  80.0   8.3  3.32  10.1  70.3  2682  21.0  46.1  24.1   17.0   
37  42.0  33.0  77.0   9.7  3.30  10.7  83.5  7462  11.3  48.7  12.4   41.0   
38  42.0  32.0  76.0   9.1  3.32  10.5  87.5  6092  17.5  45.3  13.2   29.0   
39  36.0  29.0  72.0   9.5  3.32  10.6  77.6  3437   8.1  45.5  13.8   45.0   
40  37.0  38.0  67.0  11.3  2.99  12.0  81.5  3387   3.6  50.3  13.5   56.0   
41  42.0  29.0  72.0  10.7  3.19  10.1  79.5  3508   2.2  38.3  15.7    6.0   
42  41.0  33.0  77.0  11.2  3.80   9.6  79.9  4843   2.7  38.6  14.1   11.0   
43  44.0  39.0  78.0   8.2  3.32  11.0  79.9  3768  28.6  49.5  17.5   12.0   
45  34.0  32.0  79.0   9.3  3.23   9.7  76.8  5160  17.2  45.1  15.3   31.0   
47  18.0  48.0  63.0   9.2  2.92  12.2  87.7  4253  13.7  51.2  12.0  311.0   
48  13.0  49.0  68.0   7.0  3.36  12.2  90.7  2702   3.0  51.9   9.7  105.0   
49  35.0  40.0  64.0   9.6  3.20  12.2  82.5  3626   5.7  54.3  10.1   20.0   
50  45.0  28.0  74.0  10.6  3.21  11.1  82.6  1883   3.4  41.9  12.3    5.0   
52  31.0  26.0  73.0   9.3  3.22  10.7  81.3  3249   9.5  43.9  13.6   11.0   
53  40.0  23.0  71.0  11.3  3.28  10.3  73.8  1671   2.5  47.4  13.5    5.0   
55  28.0  32.0  81.0   7.0  3.27  12.1  81.0  3665   7.5  51.6  13.2    4.0   
57  45.0  24.0  70.0  11.8  3.25  11.1  79.8  3678   1.0  44.8  14.0    7.0   
58  42.0  83.0  76.0   9.7  3.22   9.0  76.2  9699   4.8  42.2  14.5    8.0   
59  38.0  28.0  72.0   8.9  3.48  10.7  79.8  3451  11.7  37.5  13.0   14.0   

      x13    x14  x15         Y  
1    10.0   39.0   57   997.875  
3     8.0   24.0   56   982.291  
5    32.0   72.0   54  1030.380  
6    32.0   62.0   56   934.700  
7     4.0    4.0   56   899.529  
8    12.0   37.0   61  1001.902  
9     7.0   20.0   59   912.347  
10    8.0   27.0   56  1017.613  
11   63.0  278.0   58  1024.885  
12   26.0  146.0   57   970.467  
14    9.0   15.0   58   958.839  
15    1.0    1.0   54   860.101  
16    4.0   16.0   58   936.234  
17    8.0   28.0   38   871.766  
18   35.0  124.0   

In [ ]:
ilosc_wszystkich_komórek = len(dfd) * len(dfd.columns)
ilosc_wszystkich_komórek

688

In [ ]:
ilość_niepustych_komórek = dfd.count().sum()
ilość_niepustych_komórek

688

In [ ]:
ilosc_wierszy = len(dfd)
ilosc_wierszy

43

In [ ]:
ilosc_kolumn = len(dfd.columns)
ilosc_kolumn

16

In [ ]:
dfd.mean()

x1       36.581395
x2       35.186047
x3       74.813953
x4        8.846512
x5        3.284419
x6       10.965116
x7       80.123256
x8     3871.790698
x9       11.920930
x10      46.079070
x11      14.888372
x12      42.558140
x13      25.395349
x14      56.651163
x15      57.186047
Y       938.970512
dtype: float64

In [ ]:
dfd.median()

x1       37.000
x2       32.000
x3       74.000
x4        9.100
x5        3.280
x6       10.900
x7       79.900
x8     3626.000
x9       11.300
x10      45.500
x11      13.600
x12      17.000
x13       9.000
x14      28.000
x15      56.000
Y       946.185
dtype: float64

In [ ]:
dfd.var()

x1     9.248726e+01
x2     1.385360e+02
x3     2.639313e+01
x4     2.236833e+00
x5     2.216334e-02
x6     7.304208e-01
x7     2.715040e+01
x8     2.579227e+06
x9     8.342788e+01
x10    1.842074e+01
x11    1.696200e+01
x12    1.134949e+04
x13    2.883007e+03
x14    4.521137e+03
x15    3.720266e+01
Y      3.320336e+03
dtype: float64

In [ ]:
#Zadanie 2

In [3]:
import numpy as np

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/PAD colab/04/Zadanie_2.csv',sep=';',header=None )
df2

0   1   2   3  4   5   6  7  8  9
0  1   2  15 -59  9   3  75  6  7  1
1  0   5   0   4  6  16  44  7  1  1
2  7  14   3 -10  9  15  73  8  2  9
3  1   5  15 -54  5  15  35  8  6  4
4  0   8   5 -18  7  16  91  6  7  9
5  7  18  23 -90  4   8  31  0  1  7
6  2   8  20 -72  4   1  91  9  4  4
7  4  12  18 -65  6   9  76  4  9  9
8  7  15  13 -52  5   7  54  2  7  0
9  2   9  15 -56  6   1  98  4  8  4

In [ ]:
wartosci_wlasne = np.linalg.eigvals(df2)
wektory_wlasne = np.linalg.eig(df2)

In [ ]:
wartosci_wlasne

array([104.34960192 +0.j        , -23.35660516+18.84992811j,
       -23.35660516-18.84992811j,  15.92989017 +0.j        ,
        -4.99456452 +0.j        ,   0.35205717 +5.80125175j,
         0.35205717 -5.80125175j,  -1.03383491 +0.j        ,
         3.87900166 +1.42651533j,   3.87900166 -1.42651533j])

In [ ]:
wektory_wlasne

(array([104.34960192 +0.j        , -23.35660516+18.84992811j,
        -23.35660516-18.84992811j,  15.92989017 +0.j        ,
         -4.99456452 +0.j        ,   0.35205717 +5.80125175j,
          0.35205717 -5.80125175j,  -1.03383491 +0.j        ,
          3.87900166 +1.42651533j,   3.87900166 -1.42651533j]),
 array([[-0.29000475+0.j        , -0.07545445+0.07743149j,
         -0.07545445-0.07743149j, -0.03544485+0.j        ,
          0.42681634+0.j        , -0.22172831-0.29869259j,
         -0.22172831+0.29869259j,  0.41343726+0.j        ,
         -0.28670255+0.21891569j, -0.28670255-0.21891569j],
        [-0.24163153+0.j        ,  0.41229621+0.09197324j,
          0.41229621-0.09197324j,  0.45873475+0.j        ,
         -0.27056206+0.j        , -0.01331344+0.1422557j ,
         -0.01331344-0.1422557j , -0.31591047+0.j        ,
          0.41954481-0.10561864j,  0.41954481+0.10561864j],
        [-0.41060573+0.j        ,  0.37509638-0.00960818j,
          0.37509638+0.00960818j,  0.

In [ ]:
macierz_odwrotna = np.linalg.inv(df2)

In [ ]:
macierz_odwrotna

array([[ 0.47461371,  0.13269253, -0.24726695, -0.82965177,  0.28250384,
        -0.17012825,  0.58274426,  0.83686705,  0.4146721 , -1.56942847],
       [-0.38032531, -0.11226789,  0.23216372,  0.58853747, -0.2508954 ,
         0.10174485, -0.40729564, -0.58325689, -0.2335154 ,  1.11832726],
       [ 0.13559662,  0.58950334, -0.24709855, -0.58789838, -0.30170699,
        -0.12721938,  0.23740295,  1.01003036, -0.02151387, -0.64590149],
       [ 0.01425207,  0.14570726, -0.04557569, -0.12721972, -0.08945184,
        -0.03756624,  0.03910376,  0.23606066, -0.01436771, -0.11345749],
       [-0.09473246,  0.01725249,  0.19145597,  0.32960274, -0.28626296,
         0.08348529, -0.37577603, -0.27295934, -0.25855803,  0.74691827],
       [ 0.16387032,  0.10075684, -0.15404907, -0.29794662,  0.16916877,
        -0.02827782,  0.20469921,  0.28036265,  0.15086178, -0.5882585 ],
       [ 0.04288003,  0.02246462, -0.0366803 , -0.09024915,  0.04322146,
        -0.01047861,  0.06167348,  0.07009721

In [ ]:
#Zadanie 3

In [ ]:
df3a = pd.read_csv('/content/drive/MyDrive/PAD colab/04/Zadanie_3_macierz_A.csv',sep=',',header=None )
df3b = pd.read_csv('/content/drive/MyDrive/PAD colab/04/Zadanie_3_macierz_B.csv',sep=',',header=None )

In [ ]:
df3a

0    1    2
0  2.0  2.0  3.0
1  1.0  0.0  4.0
2  6.0  9.0  7.0

In [ ]:
df3b

0     1    2
0  1.0   5.0  2.0
1  6.0   6.0  4.0
2  1.0  10.0  7.0
3  5.0   8.0  2.0
4  3.0   0.0  6.0

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity(df3a,df3b)


array([[0.7970534 , 0.93075784, 0.85152689, 0.80479273, 0.86772183],
       [0.3985267 , 0.56879646, 0.57428557, 0.32694705, 0.97618706],
       [0.92108283, 0.9763075 , 0.91890016, 0.9336035 , 0.69421013]])

In [16]:
#Zadanie 4 nie zrobione
df4 = pd.read_csv('/content/drive/MyDrive/PAD colab/04/Zadanie_4.csv',sep=';')

In [17]:
df4

DateTime  DoctorID Type    City  Unnamed: 4  Unnamed: 5  \
0    16.03.2020 12:00         1   GP  Warsaw         NaN         NaN   
1    16.03.2020 12:01         1   GP  Warsaw         NaN         NaN   
2    16.03.2020 12:02         1   GP  Warsaw         NaN         NaN   
3    16.03.2020 12:03         1   GP  Warsaw         NaN         NaN   
4    16.03.2020 12:04         1   GP  Warsaw         NaN         NaN   
..                ...       ...  ...     ...         ...         ...   
194  29.03.2020 14:33         1   GP  Warsaw         NaN         NaN   
195  29.03.2020 14:34         1   GP  Warsaw         NaN         NaN   
196  29.03.2020 14:35         1   GP  Warsaw         NaN         NaN   
197  29.03.2020 14:36         1   GP  Warsaw         NaN         NaN   
198  29.03.2020 14:37         1   GP  Warsaw         NaN         NaN   

     Unnamed: 6  Unnamed: 7  
0           NaN         NaN  
1           NaN         NaN  
2           NaN         NaN  
3           NaN         NaN  
4           NaN         NaN  
..          ...         ...  
194         NaN         NaN  
195         NaN         NaN  
196         NaN         NaN  
197         NaN         NaN  
198         NaN         NaN  

[199 rows x 8 columns]

In [21]:
df4 = df4.drop(df4.columns[[-1]], axis=1)  # Wykonane 4 razy
df4

DateTime  DoctorID Type    City
0    16.03.2020 12:00         1   GP  Warsaw
1    16.03.2020 12:01         1   GP  Warsaw
2    16.03.2020 12:02         1   GP  Warsaw
3    16.03.2020 12:03         1   GP  Warsaw
4    16.03.2020 12:04         1   GP  Warsaw
..                ...       ...  ...     ...
194  29.03.2020 14:33         1   GP  Warsaw
195  29.03.2020 14:34         1   GP  Warsaw
196  29.03.2020 14:35         1   GP  Warsaw
197  29.03.2020 14:36         1   GP  Warsaw
198  29.03.2020 14:37         1   GP  Warsaw

[199 rows x 4 columns]

In [ ]:
tab = {'Date': [], 'TimeFrom': [], 'TimeTO':[], 'DoctorID':[], 'Type':[], 'City':[]}
for r in df4:
  if r[]